apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
    release: "0"
spec:
  containers:
    - name: wepapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod-5
  labels:
    app: webapp
    release: "0-5"
spec:
  containers:
    - name: wepapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
    release: "0-5"
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
