apiVersion: v1
kind: Pod
metadata:
  name: activemq-pod
  labels:
    app: activemq
spec:
  containers:
    - name: activemq
      image: richardchesterwood/k8s-fleetman-queue:release1

---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  selector:
    app: activemq
  ports:
    - name: http
      port: 8161
      targetPort: 8161
      nodePort: 30010
  type: NodePort
